name: ci-test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        name: Set up Go
        with:
          go-version: 1.19
          id: go
      - uses: actions/checkout@v2
        name: Check out code into the Go module directory


      - run: make test
        name: Test

